### ISSUE TITLE
Question on visualizing the data

### ISSUE THREAD

**Issue by GrepRunRepeat** [chahuja/language2pose#10]
Hello and thanks for your work. I was wondering if you could tell me how you were able to animate the joint values from the XML-files, although some coordinates are sometimes missing? Take for example the joint LKx_joint, which only has the x-coordinate. How would you use a 3d matplotlib plot to visualize these joints? I tried examing your code, but I can't find the place where you simply read the XML-file, parse the joint values, and visualize them.

I would be grateful for any tips.

**Comment by chahuja** [comment]
Hi, 
The XML files contain joint angles for each joint, but some of these joints only have 2 or 1 degree of motion such as LK (or Left Knee I think). So, here the assumption is that the other joint angles do not change. You can find the skeleton structure [here](https://github.com/chahuja/language2pose/blob/a65d6857d504b5c7cc154260ee946224d387da9d/src/skeleton/mmm.xml).

The preprocessing class which converts these joint angles to quaternions and then to joint positions (in Euler space) is available [here](https://github.com/chahuja/language2pose/blob/a65d6857d504b5c7cc154260ee946224d387da9d/src/data/data.py#L259) and the commands to preprocess the data is available in the Readme [here](https://github.com/chahuja/language2pose/blob/a65d6857d504b5c7cc154260ee946224d387da9d/README.md#preprocessing).

Once the joint positions are extracted it is straightforward to render these animations in matplotlib. The render function is available [here](https://github.com/chahuja/language2pose/blob/a65d6857d504b5c7cc154260ee946224d387da9d/src/utils/visualization.py#L38).

Hope you find these useful!

**Comment by GrepRunRepeat** [comment]
Thank you :)

**Comment by GrepRunRepeat** [comment]
Another question though...why are the arms of the skeleton hanging behind the its back in most of your [animations](https://www.youtube.com/watch?v=zfllpcBlAVI)? Is it the dataset or how it was preprocessed? Thanks again for your time

**Comment by chahuja** [comment]
For some reason, there was a constant bias in the shoulder joints of the skeleton provided in the dataset.  I was not able to rectify it completely, hence the artefacts.
